version: '3.8'
services:
  redis:
    image: redis:7.0.11-alpine
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 3
    ports:
      - 6379:6379
